class Examens:
    """Screening tests"""

    t_hba1c = "HbA1c"
    lipids = "Bilan lipidique (LDL, HDL, CT, TG)"
    nfs_f = "NFS, ferritinémie"
    hepatic = "ASAT, ALAT, GGT"
    renal = "Créatininémie (DFG selon CKD-EPI), Ratio albuminurie/créatininurie sur échantillon"
    iono = "Ionogramme sanguin"
    echo_aaa = "Echographie à la recherche d'un anevrysme de l'aorte abdominale"
    aod = "Rivaroxaban"
    t_aomi = "Recherche de symptomes, examen des pouls, IPS"
    aspirin = "Envisage prescription de Aspirine 75 mg"
    t_tca = "Questionnaire SCOFF de dépistage des TCA"
    pancreas = "TDM-TAP injecté à la recherche du cancer de pancréas"
    cardio = "Consultation cardiologique"
    bariatric = "Chirurgie bariatrique à discuter"
    teeth = "Consultation dentaire"
    erection = "Rechercher les signes de dysfonction érectile"
    ecg = "ECG"
    t_effort = "Epreuve d'effort"
    fibrate = "Envisager prescription de Fibrates"
    podo = "Grade podologique"
    t_hta = "Recherche de signes de HTA"
    t_cardiac_insuff = "NT-proBNP"
    echo_hepatic = "Echographie abdominale à la recherche de stéatopathie métabolique"
    t_nash = "Score FIB-4"
    t_neuropathy = "Recherche de signes de neuropathie périphérique: monofilament, pic-touche, diapason, hypotension orthostatique, sécheresse cutanée"
    t_retinopathy = "Consultation ophtalmologique à la recherche de signes de rétinopathie"
    calcic_score = "Réaliser score calcique coronaire"
    cushing = "Rechercher un syndrome de Cushing"
    vaccins = "Vaccination covid-19, grippe, pneumocoque"
    vitB12 = "Dosage de la vitamine B12"
