class Questions:
    """Questions asked"""

    q1 = "Quel est le sexe de vôtre patient ? (H/F)"
    q2 = "Quel est son âge (en années) ?"
    q3 = "Quelle est sa taille (en cm) ?"
    q4 = "Quel est son poids (en kg) "
    # Partie ATCD personnels
    q5 = "Fume-t-il où a-t-il arrêté de fumer depuis moins de 20 ans (O/N) ?"
    q6 = "Depuis combien d'années évolue le diabète ?"
    q7 = "Le diabète est-il décompensé ou difficile à équilibrer (O/N) ?"
    q8 = "Le patient presente-t-il un ATCD de cardiopathie ischémique (O/N) ?"
    q9 = "De AOMI (O/N) ?"
    q10 = "De rétinopathie (O/N) ?"
    q11 = "De neuropathie périphérique (O/N) ?"
    q12 = "De AVC ou de AIT (O/N) ?"
    q13 = "De sténose artérielle documentée (O/N) ?"
    q14 = "D'athérome carotidien (O/N) ?"
    q15 = "D'insuffisance cardiaque (O/N) ?"
    q16 = "De fibrillation auriculaire (O/N) ?"
    q17 = "De HTA ?"
    q18 = "De neuropathie autonome (signes parmi: hypotension orthostatique, dysfonction érectile, incontinence urinaire, gastroparésie, constipation) ?"
    q19 = "De pancréatite chronique (O/N) ?"
    q20 = "De syndrome d'apnées du sommeil (O/N) ?"
    q21 = "De stéato-hépatite non alcoolique (O/N) ?"
    q22 = "Le patient presente-t-il une onde q de nécrose sur un ECG (O/N) ?"
    q23 = "Présente-t-il une insuffisance ventriculaire gauche ou une hypertrophie ventriculaire gauche à l'échographie (O/N) ?"
    q24 = "Le patient peut-t-il monter 2 étages sans grande difficulté (O/N) ?"
    q25 = "A-t-il perdu du poids récemment de manière involontaire (O/N) ?"
    q26 = "Existe-t-il une dyspnée non expliquée (O/N) ?"
    q27 = "Le patient présente-t-il des signes de sécheresse cutanée (O/N) ?"
    q28 = "Est-il traité par la metformine (O/N) ?"
    q29 = "Le patient est-il en situation de reprise de l'activité physique soutenue après 45 ans (O/N) ?"
    q30 = "Le patient prsente-t-il un bas niveau socio-économique (O/N) ?"
    # Partie résultats des examens paracliniques
    q31 = "Quel est le niveau du LDL cholestérol ?"
    q32 = "Quel est le niveau de cholestérol total ?"
    q33 = "Quel est le DFG du patient ?"
    q34 = "Quel est la valeur de protéinurie ? Si absente, indiquer 0."
    q35 = "Le dernier HbA1c mesuré ?"
    q36 = "Quelle est la valeur de la numération plaquettaire (en G/L) ?"
    q37 = "Quelle est la valeur des ALAT/ASAT ?"
    # Partie ATCD familiaux
    q38 = "Dans les antécédents familiaux de 1er degré existe-t-il une histoire d'anévrysme de l'aorte abdominale (O/N) ?"
    q39 = "Dans les antécédents familiaux de 1er degré existe-t-il une histoire d'hypercholestérolémie familiale (O/N) ?"
    q40 = "Dans les antécédents familiaux de premier degré existe-t-il une histoire de cardiopathie ischémique (O/N) ?"
