# Generated by Django 4.2.5 on 2023-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
