# Generated by Django 4.2.5 on 2023-10-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_question_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
