# Generated by Django 4.2.5 on 2023-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_text',
            field=models.TextField(default='Texte', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
