# Generated by Django 4.2.5 on 2023-10-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_screeningtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningtest',
            name='source_link',
            field=models.TextField(),
        ),
    ]
