# Generated by Django 4.2.5 on 2023-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_screeningtest_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningtest',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
