# Generated by Django 4.2.5 on 2023-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_screeningtest_source_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningtest',
            name='source_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='screeningtest',
            name='source_text',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
