# Generated by Django 4.2.5 on 2023-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_screeningtest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningtest',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='screeningtest',
            name='source_text',
        ),
        migrations.AddField(
            model_name='screeningtest',
            name='sources',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
