# Generated by Django 4.2.5 on 2023-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_screeningtest_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='screening_test_images/'),
        ),
    ]
