# Generated by Django 4.2.5 on 2023-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_screeningtest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningtest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
