# Generated by Django 4.2.5 on 2023-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_screeningtest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtest',
            name='ordo',
            field=models.FileField(blank=True, null=True, upload_to='ordonnances/'),
        ),
    ]
